### ISSUE TITLE
Add Keychain reference on window object

### ISSUE THREAD

**Issue by jacquesdev** [ionic-team/cordova-plugin-ios-keychain#1]
I am using the following plugin: [ng-persist](https://github.com/AlexDisler/ng-persist) , which uses shazron's original KeychainPlugin as a dependency.

I am trying to swap out this fork instead for shazron's original KeychainPlugin, and it looks like the original plugin adds a reference to the Keychain object on the window object [here](https://github.com/shazron/KeychainPlugin/search?utf8=%E2%9C%93&q=window). This reference is used in [ng-persist](https://github.com/AlexDisler/ng-persist), and so using the current fork doesn't work because it can't find the Keychain object (on the window object).

If you could add this reference - or suggest an alternative fix that would be great!

**Comment by jacquesdev** [comment]
@mlynch - is this something you would be able to do by any chance?

**Comment by mlynch** [comment]
I have that same line in here: https://github.com/driftyco/cordova-plugin-ios-keychain/blob/master/plugin.xml#L18

What's not working for you guys?

**Comment by jacquesdev** [comment]
Hmm, ok sorry I did not see that before. Basically when I use this plugin with ng-persist, I get the error that window.Keychain does not exist, whereas with the original plugin it does not seem to be a problem, but could be part of my setup.

I will play around with it some more to see if I can figure it out.

**Comment by HeyHugo** [comment]
I believe I'm facing the same problem with ng-persist plugin.

```
Object is not a constructor (evaluating 'new window.Keychain')
```

The piece of code using $persist is wrapped in $ionicPlatform.ready so everything should be loaded at this point.

**Comment by jacquesdev** [comment]
@HeyHugo - please see my comments here: https://github.com/AlexDisler/ng-persist/issues/6

Also, I have added the PR as mentioned: https://github.com/AlexDisler/ng-persist/issues/7
