### ISSUE TITLE
Keychain.get always returns null on iOS8

### ISSUE THREAD

**Issue by jdart** [ionic-team/cordova-plugin-ios-keychain#10]
Everything seems to work on iOS 9.3, but on iOS 8 I always get back null. Is there anything I can do to help debug this? I've stepped through some Obj-c code and all I can determine is that `OSStatus status = SecItemCopyMatching((__bridge CFDictionaryRef)query, &data);` results in a status of -50 which I believe means "client has neither application-identifier nor keychain-access-groups entitlements".

Edit: cordova-ios@4.2.1, xcode 7.3.1

**Comment by ddennis** [comment]
Hi I am running IOS 9.2.1 and it seems like i have the same problem.
The Keychain.get(function(value){}) value is always **_null**_

cordova version: 6.3.1, xcode 7.3.1

**Comment by oxigenao** [comment]
same problem here, always return null  ios 10 and xcode-beta 8

**Comment by mlynch** [comment]
Hmm, not able to reproduce this. Are you sure you set a value properly?

Do you have more code to share?

**Comment by jdart** [comment]
I had been trying really simple cases, like doing a set and then immediately after doing a get.

**Comment by mlynch** [comment]
@jdart can you give the new version in master a try? It might have fixed that anyways. Also, if not, try separating them with a setTimeout just to see, I'm curious...

**Comment by william-beange-hs** [comment]
not working for me either

**Comment by amitvshah25** [comment]
not working for me as well with ios 11
