### ISSUE TITLE
Whats the purpose of the "servicename " param removal?

### ISSUE THREAD

**Issue by johnborges** [ionic-team/cordova-plugin-ios-keychain#11]
I noticed that the `Keychain.set()` no longer accepts the `servicename` param. Any reason why?

**Comment by raminnoodle** [comment]
I was wondering the same. Does it use an implied servicename based on the application now?

**Comment by mlynch** [comment]
I was unclear what value that offered. Instead, the keychain library I'm using now just uses the bundle identifier for the app as the service name.

I'm open to suggestions or ideas on what the pros/cons of this might be.
