### ISSUE TITLE
plugin doesn't work with iOS 10

### ISSUE THREAD

**Issue by jas67** [ionic-team/cordova-plugin-ios-keychain#12]
I can not get the plugin to work with iOS 10 targets.   I am testing with both SDK 9.3 and SDK 10.0.
Builds with both SDKs work fine on iOS 9.3 targets, but, not on iOS 10 targets.

Something, has apparently changed with how iOS 10 handles keychains.

**Comment by jas67** [comment]
I was able to get it working by turning on "Keychain Sharing" in the Capabilities tab of my project in Xcode.

**Comment by jacquesdev** [comment]
I am not sure how the capabilities work, but is there any way that when the plugin is installed, that it could turn Keychain Sharing on automatically? (for iOS10?)

**Comment by jas67** [comment]
https://github.com/Telerik-Verified-Plugins/Keychain-Sharing https://github.com/Telerik-Verified-Plugins/Keychain-Sharing

cordova plugin add --variable KEYCHAIN_ACCESS_GROUP=com.company.app https://github.com/Telerik-Verified-Plugins/Keychain-Sharing

On Sep 20, 2016, at 12:13 PM, Jacques de Villiers <notifications@github.com<mailto:notifications@github.com>> wrote:

I am not sure how the capabilities work, but is there any way that when the plugin is installed, that it could turn Keychain Sharing on automatically? (for iOS10?)
