### ISSUE TITLE
Transitioning from shazron to diftyco?

### ISSUE THREAD

**Issue by scottjpearson** [ionic-team/cordova-plugin-ios-keychain#13]
I am using shazron's KeyChain to store a pin. How can I read that pin and store it afresh using diftyco's updated plugin? I need to do this under an iOS 10 build.

Thanks,
Scott

**Comment by mlynch** [comment]
Hi Scott, you should be able to just use the new name with this plugin. Underneath we're both using the same API, this version of the keychain is just a bit more up to date with iOS 9 and 10.
