### ISSUE TITLE
.get return null on iOS 10.1

### ISSUE THREAD

**Issue by afilhodaniel** [ionic-team/cordova-plugin-ios-keychain#15]
Hi,

The .get resource always return null on iOS 10. But, on any other version its fine.

Any error is throwed. The .get executes successfully, but without data.

**Comment by Sravan-Nayini** [comment]
Yes Even I am facing this issue.get() always returning null.

**Comment by Sravan-Nayini** [comment]
any workaround please?

**Comment by Sravan-Nayini** [comment]
follow this step.
Add KeyChain Entitlement, Go to project settings->Capabilities->Keychain Sharing->Add Keychain Groups+Turn On

Now working fine

**Comment by afilhodaniel** [comment]
@Sravan-Nayini yes, this works fine! Thanks!

**Comment by johnborges** [comment]
@Sravan-Nayini suggestion above doesn't work for me.

**Comment by mlynch** [comment]
Anyone else have thoughts on whether @Sravan-Nayini's suggestion works? Standing by and will update/close issue accordingly

**Comment by rachelpopa** [comment]
I am seeing the same thing with the latest version.  Sravan-Nayini 's suggestion does not work for me and I always use keychain sharing anyways.  It is resulting in a success but the value returned is null.  This is on iOS 10.2

**Comment by marcosbrigante** [comment]
I see the null problem on simulator, on device it works nicely.

**Comment by mlynch** [comment]
Looks like a simulator limitation
