### ISSUE TITLE
Cannot read property 'replace' of null

### ISSUE THREAD

**Issue by laurent-bettin** [ionic-team/cordova-plugin-ios-keychain#16]
Hi,

Got an error when calling getJson method on a non exisiting key as value is null when the replace method is invoked.

Shouldn't value be checked or did I misunderstood something?
Thx

https://github.com/driftyco/cordova-plugin-ios-keychain/blob/a30e630017f1504cc53e9d992160210f058d323e/www/keychain.js#L52

**Comment by mlynch** [comment]
Should be patched up and ready to get back into the good fight. Try master and let me know? Thanks.

**Comment by laurent-bettin** [comment]
Sounds good.
Thanks.
