### ISSUE TITLE
iCloud enable/disable option

### ISSUE THREAD

**Issue by okonon** [ionic-team/cordova-plugin-ios-keychain#2]
Is there a way to enable / disable iCloud Keychain sync?

**Comment by jacquesdev** [comment]
@mlynch - I believe the changes were done after your fork, as part of this commit:
https://github.com/shazron/KeychainPlugin/commit/4399889816bd5898f0359dc85a5aae2f9f793ea7

Could be quick to add this option here?

**Comment by johnreitano** [comment]
I need this functionality too. Would it be possible to merge in those changes?

**Comment by mlynch** [comment]
Got it, I'll look into how I might do this with the keychain engine underneath this

**Comment by mlynch** [comment]
Hey, just pushed a branch which (in theory) adds support for iCloud. Mind testing this and let me know if it's working for you? This adds a new flag to `set` which is a boolean to sync or not sync:

https://github.com/driftyco/cordova-plugin-ios-keychain/tree/wip-icloud

**Comment by atsats** [comment]
My preliminary testing indicates that that the new flag added to the set function (which controls whether the key gets synched to iCloud) works as designed when the value is false.

**Comment by tommykk** [comment]
Hey, is there any chance of this getting in soon? I could really do with this feature!

**Comment by mlynch** [comment]
Hi @tomkeble, it's available now. Just install the plugin from this repo and you're golden
