### ISSUE TITLE
Is it possible to read values with this plugin saved in Safari?

### ISSUE THREAD

**Issue by extempl** [ionic-team/cordova-plugin-ios-keychain#26]
I tried to look for answer on the web with no luck.
So just asking here.
Is it possible to log in to the app form with data saved with Safari in keychain? Or is there some restriction from access to keychain data from other apps?

I see that this is possible to read any saved data with `Keychain Access` but you need to enter master password. Maybe on mobile it may be somehow shared via TouchID?

Thanks in advance.

**Comment by mlynch** [comment]
No, and that seems like a big security issue  if you could
