### ISSUE TITLE
Not iCloud Keychain enabled

### ISSUE THREAD

**Issue by abuist** [ionic-team/cordova-plugin-ios-keychain#27]
Even though the documentation states it is iCloud enabled it is not. It is missing the kSecAttrSynchronizable attribute to allow synchronization. I was having issues with getting it to work properly and by adding the kSecAttrSynchronizable to the basequery attributes in A0SimpleKeychain.m I was able to resolve the issue, as provided by the wip-icloud branch. 

I see that Pull 17 seems to address an issue with that branch. 

Andy

**Comment by mlynch** [comment]
Merged #17
