### ISSUE TITLE
Crashing 

### ISSUE THREAD

**Issue by mike-nelson** [ionic-team/cordova-plugin-ios-keychain#7]
I upgraded from shazron version 3.0.0 to driftyco 3.0.1 and it just froze up when calling.

I diffed the changes and can't see anything obvious, just looks like an extra param added for sync yes/no. 

So i forked shazron:old and am using that version which works perfectly. 

I didn't spend too much time investigating exact fault as it already took me hours to track it down to this plugin upgrade. I recently upgraded to ios 10, not sure if related.

**Comment by jacquesdev** [comment]
@mike-nelson - I think you would need to update some of your calls since for example you no longer need to instantiate an instance of Keychain but can use it directly. Also the three method names have changed. They are now:
- Keychain.get()
- Keychain.set()
- Keychain.remove()

**Comment by mike-nelson** [comment]
This should NOT be a point release!

**Comment by mlynch** [comment]
Closing, looks like this is all good?
