### ISSUE TITLE
EXC_BAD_ACCESS on iOS 9.2

### ISSUE THREAD

**Issue by jdart** [ionic-team/cordova-plugin-ios-keychain#9]
I'm getting an error when using this plugin on a device running iOS 9.2. Any idea what might be going on?

![error](https://cloud.githubusercontent.com/assets/118674/17908067/7b1130b2-6944-11e6-936e-3ececa11ffdb.png)

Edit: cordova-ios@4.2.1, xcode 7.3.1

**Comment by mlynch** [comment]
Thanks for the report, I'm able to reproduce and looking into it now

**Comment by mlynch** [comment]
@jdart a couple of questions: what does your `Keychain` call look like? From what I gather, this error happens when you omit the `touchIDMessage` from the `get` call. However, making sure `get` doesn't have to use keychain is part of #5

**Comment by mlynch** [comment]
This is fixed and I now use a filler string if it's not provided
